/******************************************************************************
 * Filename:       TiPassword_service.c
 *
 * Description:    This file contains the implementation of the service.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3135.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.8
 *                 Time:        Sun Mar 26 2017 21:15:26 GMT+02:00
 *

 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **********************************************************************************/


/*********************************************************************
 * INCLUDES
 */
#include <string.h>
#include <xdc/runtime/System.h>

//#define xdc_runtime_Log_DISABLE_ALL 1  // Add to disable logs from this file
#include <xdc/runtime/Log.h>
#include <xdc/runtime/Diags.h>

#include "bcomdef.h"
#include "OSAL.h"
#include "linkdb.h"
#include "att.h"
#include "gatt.h"
#include "gatt_uuid.h"
#include "gattservapp.h"
#include "gapbondmgr.h"

#ifdef ICALL_LITE
#  include "icall_api.h" // Only exists for 3.x stack version, so use ifdef.
#endif

#include "tipassword_service.h"

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * CONSTANTS
 */

/*********************************************************************
 * TYPEDEFS
 */

/*********************************************************************
* GLOBAL VARIABLES
*/

// TiPassword_service Service UUID
CONST uint8_t TipasswordServiceUUID[ATT_UUID_SIZE] =
{
  TIPASSWORD_SERVICE_SERV_UUID_BASE128(TIPASSWORD_SERVICE_SERV_UUID)
};

// Password UUID
CONST uint8_t ts_PasswordUUID[ATT_UUID_SIZE] =
{
  TS_PASSWORD_UUID_BASE128(TS_PASSWORD_UUID)
};

// PasswordID UUID
CONST uint8_t ts_PasswordIDUUID[ATT_UUID_SIZE] =
{
  TS_PASSWORDID_UUID_BASE128(TS_PASSWORDID_UUID)
};

// UserName UUID
CONST uint8_t ts_UserNameUUID[ATT_UUID_SIZE] =
{
  TS_USERNAME_UUID_BASE128(TS_USERNAME_UUID)
};


/*********************************************************************
 * LOCAL VARIABLES
 */

static TipasswordServiceCBs_t *pAppCBs = NULL;
static uint8_t ts_icall_rsp_task_id = INVALID_TASK_ID;

/*********************************************************************
* Profile Attributes - variables
*/

// Service declaration
static CONST gattAttrType_t TipasswordServiceDecl = { ATT_UUID_SIZE, TipasswordServiceUUID };

// Characteristic "Password" Properties (for declaration)
static uint8_t ts_PasswordProps = GATT_PROP_NOTIFY | GATT_PROP_READ;

// Characteristic "Password" Value variable
static uint8_t ts_PasswordVal[TS_PASSWORD_LEN] = {0};

// Length of data in characteristic "Password" Value variable, initialized to minimal size.
static uint16_t ts_PasswordValLen = TS_PASSWORD_LEN_MIN;

// Characteristic "Password" Client Characteristic Configuration Descriptor
static gattCharCfg_t *ts_PasswordConfig;



// Characteristic "PasswordID" Properties (for declaration)
static uint8_t ts_PasswordIDProps = GATT_PROP_WRITE;

// Characteristic "PasswordID" Value variable
static uint8_t ts_PasswordIDVal[TS_PASSWORDID_LEN] = {0};

// Length of data in characteristic "PasswordID" Value variable, initialized to minimal size.
static uint16_t ts_PasswordIDValLen = TS_PASSWORDID_LEN_MIN;



// Characteristic "UserName" Properties (for declaration)
static uint8_t ts_UserNameProps = GATT_PROP_NOTIFY | GATT_PROP_READ;

// Characteristic "UserName" Value variable
static uint8_t ts_UserNameVal[TS_USERNAME_LEN] = {0};

// Length of data in characteristic "UserName" Value variable, initialized to minimal size.
static uint16_t ts_UserNameValLen = TS_USERNAME_LEN_MIN;

// Characteristic "UserName" Client Characteristic Configuration Descriptor
static gattCharCfg_t *ts_UserNameConfig;



/*********************************************************************
* Profile Attributes - Table
*/

static gattAttribute_t TiPassword_serviceAttrTbl[] =
{
  // TiPassword_service Service Declaration
  {
    { ATT_BT_UUID_SIZE, primaryServiceUUID },
    GATT_PERMIT_READ,
    0,
    (uint8_t *)&TipasswordServiceDecl
  },
    // Password Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &ts_PasswordProps
    },
      // Password Characteristic Value
      {
        { ATT_UUID_SIZE, ts_PasswordUUID },
        GATT_PERMIT_READ,
        0,
        ts_PasswordVal
      },
      // Password CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&ts_PasswordConfig
      },
    // PasswordID Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &ts_PasswordIDProps
    },
      // PasswordID Characteristic Value
      {
        { ATT_UUID_SIZE, ts_PasswordIDUUID },
        GATT_PERMIT_WRITE,
        0,
        ts_PasswordIDVal
      },
    // UserName Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &ts_UserNameProps
    },
      // UserName Characteristic Value
      {
        { ATT_UUID_SIZE, ts_UserNameUUID },
        GATT_PERMIT_READ,
        0,
        ts_UserNameVal
      },
      // UserName CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&ts_UserNameConfig
      },
};

/*********************************************************************
 * LOCAL FUNCTIONS
 */
static bStatus_t TiPassword_service_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                           uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                           uint16_t maxLen, uint8_t method );
static bStatus_t TiPassword_service_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                            uint8_t *pValue, uint16_t len, uint16_t offset,
                                            uint8_t method );

/*********************************************************************
 * PROFILE CALLBACKS
 */
// Simple Profile Service Callbacks
CONST gattServiceCBs_t TiPassword_serviceCBs =
{
  TiPassword_service_ReadAttrCB,  // Read callback function pointer
  TiPassword_service_WriteAttrCB, // Write callback function pointer
  NULL                       // Authorization callback function pointer
};

/*********************************************************************
* PUBLIC FUNCTIONS
*/

/*
 * TipasswordService_AddService- Initializes the TipasswordService service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t TipasswordService_AddService( uint8_t rspTaskId )
{
  uint8_t status;

  // Allocate Client Characteristic Configuration table
  ts_PasswordConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( ts_PasswordConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, ts_PasswordConfig );
  // Allocate Client Characteristic Configuration table
  ts_UserNameConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( ts_UserNameConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, ts_UserNameConfig );
  // Register GATT attribute list and CBs with GATT Server App
  status = GATTServApp_RegisterService( TiPassword_serviceAttrTbl,
                                        GATT_NUM_ATTRS( TiPassword_serviceAttrTbl ),
                                        GATT_MAX_ENCRYPT_KEY_SIZE,
                                        &TiPassword_serviceCBs );
  Log_info1("Registered service, %d attributes", (IArg)GATT_NUM_ATTRS( TiPassword_serviceAttrTbl ));
  ts_icall_rsp_task_id = rspTaskId;

  return ( status );
}

/*
 * TipasswordService_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
bStatus_t TipasswordService_RegisterAppCBs( TipasswordServiceCBs_t *appCallbacks )
{
  if ( appCallbacks )
  {
    pAppCBs = appCallbacks;
    Log_info1("Registered callbacks to application. Struct %p", (IArg)appCallbacks);
    return ( SUCCESS );
  }
  else
  {
    Log_warning0("Null pointer given for app callbacks.");
    return ( FAILURE );
  }
}

/*
 * TipasswordService_SetParameter - Set a TipasswordService parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t TipasswordService_SetParameter( uint8_t param, uint16_t len, void *value )
{
  bStatus_t ret = SUCCESS;
  uint8_t  *pAttrVal;
  uint16_t *pValLen;
  uint16_t valMinLen;
  uint16_t valMaxLen;
  uint8_t sendNotiInd = FALSE;
  gattCharCfg_t *attrConfig;
  uint8_t needAuth;
  bStatus_t status;

  switch ( param )
  {
    case TS_PASSWORD_ID:
      pAttrVal  =  ts_PasswordVal;
      pValLen   = &ts_PasswordValLen;
      valMinLen =  TS_PASSWORD_LEN_MIN;
      valMaxLen =  TS_PASSWORD_LEN;
      sendNotiInd = TRUE;
      attrConfig  = ts_PasswordConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"Password", (IArg)len);
      break;

    case TS_USERNAME_ID:
      pAttrVal  =  ts_UserNameVal;
      pValLen   = &ts_UserNameValLen;
      valMinLen =  TS_USERNAME_LEN_MIN;
      valMaxLen =  TS_USERNAME_LEN;
      sendNotiInd = TRUE;
      attrConfig  = ts_UserNameConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"UserName", (IArg)len);
      break;

    default:
      Log_error1("SetParameter: Parameter #%d not valid.", (IArg)param);
      return INVALIDPARAMETER;
  }

  // Check bounds, update value and send notification or indication if possible.
  if ( len <= valMaxLen && len >= valMinLen )
  {
    memcpy(pAttrVal, value, len);
    *pValLen = len; // Update length for read and get.

    if (sendNotiInd)
    {
      Log_info2("Transmitting noti/ind- connHandle %d, %s", (IArg)attrConfig[0].connHandle,
                                                    (IArg)( (attrConfig[0].value==0)?"Noti/ind disabled":
                                                    (attrConfig[0].value==1)?"Notification enabled":
                                                     "Indication enabled" ) );
      // Try to send notification.
      status = GATTServApp_ProcessCharCfg( attrConfig, pAttrVal, needAuth,
                                  TiPassword_serviceAttrTbl, GATT_NUM_ATTRS( TiPassword_serviceAttrTbl ),
                                  ts_icall_rsp_task_id,  TiPassword_service_ReadAttrCB);
    }
  }
  else
  {
    Log_error3("Length outside bounds: Len: %d MinLen: %d MaxLen: %d.", (IArg)len, (IArg)valMinLen, (IArg)valMaxLen);
    ret = bleInvalidRange;
  }

  return ret;
}


/*
 * TipasswordService_GetParameter - Get a TipasswordService parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t TipasswordService_GetParameter( uint8_t param, uint16_t *len, void *value )
{
  bStatus_t ret = SUCCESS;
  switch ( param )
  {
    case TS_PASSWORDID_ID:
      *len = MIN(*len, ts_PasswordIDValLen);
      memcpy(value, ts_PasswordIDVal, *len);
      Log_info2("GetParameter : %s returning %d bytes", (IArg)"PasswordID", (IArg)*len);
      break;

    default:
      Log_error1("GetParameter: Parameter #%d not valid.", (IArg)param);
      ret = INVALIDPARAMETER;
      break;
  }
  return ret;
}

/*********************************************************************
 * @internal
 * @fn          TiPassword_service_findCharParamId
 *
 * @brief       Find the logical param id of an attribute in the service's attr table.
 *
 *              Works only for Characteristic Value attributes and
 *              Client Characteristic Configuration Descriptor attributes.
 *
 * @param       pAttr - pointer to attribute
 *
 * @return      uint8_t paramID (ref TiPassword_service.h) or 0xFF if not found.
 */
static uint8_t TiPassword_service_findCharParamId(gattAttribute_t *pAttr)
{
  // Is this a Client Characteristic Configuration Descriptor?
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
    return TiPassword_service_findCharParamId(pAttr - 1); // Assume the value attribute precedes CCCD and recurse

  // Is this attribute in "Password"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, ts_PasswordUUID, pAttr->type.len))
    return TS_PASSWORD_ID;

  // Is this attribute in "PasswordID"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, ts_PasswordIDUUID, pAttr->type.len))
    return TS_PASSWORDID_ID;

  // Is this attribute in "UserName"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, ts_UserNameUUID, pAttr->type.len))
    return TS_USERNAME_ID;

  else
    return 0xFF; // Not found. Return invalid.
}

/*********************************************************************
 * @fn          TiPassword_service_ReadAttrCB
 *
 * @brief       Read an attribute.
 *
 * @param       connHandle - connection message was received on
 * @param       pAttr - pointer to attribute
 * @param       pValue - pointer to data to be read
 * @param       pLen - length of data to be read
 * @param       offset - offset of the first octet to be read
 * @param       maxLen - maximum length of data to be read
 * @param       method - type of read message
 *
 * @return      SUCCESS, blePending or Failure
 */
static bStatus_t TiPassword_service_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                       uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                       uint16_t maxLen, uint8_t method )
{
  bStatus_t status = SUCCESS;
  uint16_t valueLen;
  uint8_t paramID = 0xFF;

  // Find settings for the characteristic to be read.
  paramID = TiPassword_service_findCharParamId( pAttr );
  switch ( paramID )
  {
    case TS_PASSWORD_ID:
      valueLen = ts_PasswordValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"Password",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for Password can be inserted here */
      break;

    case TS_USERNAME_ID:
      valueLen = ts_UserNameValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"UserName",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for UserName can be inserted here */
      break;

    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
  // Check bounds and return the value
  if ( offset > valueLen )  // Prevent malicious ATT ReadBlob offsets.
  {
    Log_error0("An invalid offset was requested.");
    status = ATT_ERR_INVALID_OFFSET;
  }
  else
  {
    *pLen = MIN(maxLen, valueLen - offset);  // Transmit as much as possible
    memcpy(pValue, pAttr->pValue + offset, *pLen);
  }

  return status;
}

/*********************************************************************
 * @fn      TiPassword_service_WriteAttrCB
 *
 * @brief   Validate attribute data prior to a write operation
 *
 * @param   connHandle - connection message was received on
 * @param   pAttr - pointer to attribute
 * @param   pValue - pointer to data to be written
 * @param   len - length of data
 * @param   offset - offset of the first octet to be written
 * @param   method - type of write message
 *
 * @return  SUCCESS, blePending or Failure
 */
static bStatus_t TiPassword_service_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                        uint8_t *pValue, uint16_t len, uint16_t offset,
                                        uint8_t method )
{
  bStatus_t status  = SUCCESS;
  uint8_t   paramID = 0xFF;
  uint8_t   changeParamID = 0xFF;
  uint16_t writeLenMin;
  uint16_t writeLenMax;
  uint16_t *pValueLenVar;

  // See if request is regarding a Client Characterisic Configuration
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
  {
    // Allow notification and indication, but do not check if really allowed per CCCD.
    status = GATTServApp_ProcessCCCWriteReq( connHandle, pAttr, pValue, len,
                                             offset, GATT_CLIENT_CFG_NOTIFY |
                                                     GATT_CLIENT_CFG_INDICATE );
    if (SUCCESS == status && pAppCBs && pAppCBs->pfnCfgChangeCb)
       pAppCBs->pfnCfgChangeCb( connHandle, TIPASSWORD_SERVICE_SERV_UUID,
                                TiPassword_service_findCharParamId(pAttr), pValue, len );

     return status;
  }

  // Find settings for the characteristic to be written.
  paramID = TiPassword_service_findCharParamId( pAttr );
  switch ( paramID )
  {
    case TS_PASSWORDID_ID:
      writeLenMin  = TS_PASSWORDID_LEN_MIN;
      writeLenMax  = TS_PASSWORDID_LEN;
      pValueLenVar = &ts_PasswordIDValLen;

      Log_info5("WriteAttrCB : %s connHandle(%d) len(%d) offset(%d) method(0x%02x)",
                 (IArg)"PasswordID",
                 (IArg)connHandle,
                 (IArg)len,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for PasswordID can be inserted here */
      break;

    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
  // Check whether the length is within bounds.
  if ( offset >= writeLenMax )
  {
    Log_error0("An invalid offset was requested.");
    status = ATT_ERR_INVALID_OFFSET;
  }
  else if ( offset + len > writeLenMax )
  {
    Log_error0("Invalid value length was received.");
    status = ATT_ERR_INVALID_VALUE_SIZE;
  }
  else if ( offset + len < writeLenMin && ( method == ATT_EXECUTE_WRITE_REQ || method == ATT_WRITE_REQ ) )
  {
    // Refuse writes that are lower than minimum.
    // Note: Cannot determine if a Reliable Write (to several chars) is finished, so those will
    //       only be refused if this attribute is the last in the queue (method is execute).
    //       Otherwise, reliable writes are accepted and parsed piecemeal.
    Log_error0("Invalid value length was received.");
    status = ATT_ERR_INVALID_VALUE_SIZE;
  }
  else
  {
    // Copy pValue into the variable we point to from the attribute table.
    memcpy(pAttr->pValue + offset, pValue, len);

    // Only notify application and update length if enough data is written.
    //
    // Note: If reliable writes are used (meaning several attributes are written to using ATT PrepareWrite),
    //       the application will get a callback for every write with an offset + len larger than _LEN_MIN.
    // Note: For Long Writes (ATT Prepare + Execute towards only one attribute) only one callback will be issued,
    //       because the write fragments are concatenated before being sent here.
    if ( offset + len >= writeLenMin )
    {
      changeParamID = paramID;
      *pValueLenVar = offset + len; // Update data length.
    }
  }

  // Let the application know something changed (if it did) by using the
  // callback it registered earlier (if it did).
  if (changeParamID != 0xFF)
    if ( pAppCBs && pAppCBs->pfnChangeCb )
      pAppCBs->pfnChangeCb( connHandle, TIPASSWORD_SERVICE_SERV_UUID, paramID, pValue, len+offset ); // Call app function from stack task context.

  return status;
}
