/******************************************************************************
 * Filename:       TiPassword_service.h
 *
 * Description:    This file contains the TiPassword_service service definitions and
 *                 prototypes.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3135.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.8
 *                 Time:        Sun Mar 26 2017 21:15:26 GMT+02:00
 *

 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef _TIPASSWORD_SERVICE_H_
#define _TIPASSWORD_SERVICE_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include <bcomdef.h>

/*********************************************************************
 * CONSTANTS
 */
// Service UUID
#define TIPASSWORD_SERVICE_SERV_UUID 0x0353
#define TIPASSWORD_SERVICE_SERV_UUID_BASE128(uuid) 0xFD, 0xAE, 0xB8, 0x1F, 0x89, 0x62, 0x28, 0x83, 0x1A, 0x48, 0xFE, 0x17, LO_UINT16(uuid), HI_UINT16(uuid), 0x6B, 0xCF

// Password Characteristic defines
#define TS_PASSWORD_ID                 0
#define TS_PASSWORD_UUID               0x44AC
#define TS_PASSWORD_UUID_BASE128(uuid) 0xFD, 0xAE, 0xB8, 0x1F, 0x89, 0x62, 0x28, 0x83, 0x1A, 0x48, 0xFE, 0x17, LO_UINT16(uuid), HI_UINT16(uuid), 0x6B, 0xCF
#define TS_PASSWORD_LEN                20
#define TS_PASSWORD_LEN_MIN            1

// PasswordID Characteristic defines
#define TS_PASSWORDID_ID                 1
#define TS_PASSWORDID_UUID               0x9FB0
#define TS_PASSWORDID_UUID_BASE128(uuid) 0xFD, 0xAE, 0xB8, 0x1F, 0x89, 0x62, 0x28, 0x83, 0x1A, 0x48, 0xFE, 0x17, LO_UINT16(uuid), HI_UINT16(uuid), 0x6B, 0xCF
#define TS_PASSWORDID_LEN                1
#define TS_PASSWORDID_LEN_MIN            1

// UserName Characteristic defines
#define TS_USERNAME_ID                 2
#define TS_USERNAME_UUID               0x0E6F
#define TS_USERNAME_UUID_BASE128(uuid) 0xFD, 0xAE, 0xB8, 0x1F, 0x89, 0x62, 0x28, 0x83, 0x1A, 0x48, 0xFE, 0x17, LO_UINT16(uuid), HI_UINT16(uuid), 0x6B, 0xCF
#define TS_USERNAME_LEN                20
#define TS_USERNAME_LEN_MIN            1

/*********************************************************************
 * TYPEDEFS
 */

// Fields in characteristic "Password"

// Fields in characteristic "PasswordID"

// Fields in characteristic "UserName"

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * Profile Callbacks
 */

// Callback when a characteristic value has changed
typedef void (*TipasswordServiceChange_t)( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );

typedef struct
{
  TipasswordServiceChange_t        pfnChangeCb;     // Called when characteristic value changes
  TipasswordServiceChange_t        pfnCfgChangeCb;  // Called when characteristic CCCD changes
} TipasswordServiceCBs_t;



/*********************************************************************
 * API FUNCTIONS
 */


/*
 * TipasswordService_AddService- Initializes the TipasswordService service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t TipasswordService_AddService( uint8_t rspTaskId );

/*
 * TipasswordService_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
extern bStatus_t TipasswordService_RegisterAppCBs( TipasswordServiceCBs_t *appCallbacks );

/*
 * TipasswordService_SetParameter - Set a TipasswordService parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t TipasswordService_SetParameter( uint8_t param, uint16_t len, void *value );

/*
 * TipasswordService_GetParameter - Get a TipasswordService parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t TipasswordService_GetParameter( uint8_t param, uint16_t *len, void *value );

/*********************************************************************
*********************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* _TIPASSWORD_SERVICE_H_ */

